WebApplication11/Models/CHUDE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUDE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUDE()
        {
            this.DOCHOIs = new HashSet<DOCHOI>();
        }
    
        public int MaCD { get; set; }
        public string Tenchude { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCHOI> DOCHOIs { get; set; }
    }
}

WebApplication11/Models/THUONGHIEU.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication11.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THUONGHIEU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THUONGHIEU()
        {
            this.DOCHOIs = new HashSet<DOCHOI>();
        }
    
        public int MaTH { get; set; }
        public string Tenthuonghieu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOCHOI> DOCHOIs { get; set; }
    }
}

WebApplication11/Controllers/NguoidungController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication11.Models;

namespace WebApplication11.Controllers
{
    public class NguoidungController : Controller
    {
        // GET: Nguoidung
        public ActionResult Index()
        {
            return View();
        }
        QLBANDOCHOIEntities1 db = new QLBANDOCHOIEntities1();
        public ActionResult Dangky()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Dangky(FormCollection collection ,KHACHHANG kh)
        {
            var hoten = collection["HotenKH"];
            var diachi = collection["DiachiKH"];
            var dienthoai = collection["DienthoaiKH"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var emai = collection["Email"];

            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên khách hàng không được để trống";
            }
            else if (String.IsNullOrEmpty(diachi))
            {
                ViewData["Loi2"] = "Không được để trống địa chỉ";
            }
            else if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi3"] = "Phải nhập số điện thoại";
            }
            else if(String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi4"] = "Tên đăng nhập không được để trống";
            }
            else if(String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi5"] = "Phải nhập mật khẩu";
            }
            else if (String.IsNullOrEmpty(emai))
            {
                ViewData["Loi6"] = "Không được để trống Email";
            }
            else
            {
                kh.HotenKH = hoten;
                kh.DiachiKH = diachi;
                kh.DienthoaiKH = dienthoai;
                kh.TenDN = tendn;
                kh.Matkhau = matkhau;
                kh.Email = emai;
                db.KHACHHANGs.Add(kh);
                db.SaveChanges();
                return RedirectToAction("Dangnhap");
            }
            return this.Dangky();
        }
        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }

        public ActionResult Dangnhap(FormCollection collection)
        {
            var tendn = collection["username"];
            var matkhau = collection["password"];
            if(String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Tên đăng nhập không được để trống";
            }
            else if(String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Mật khẩu không được để trống";
            }
                else
                {
                    KHACHHANG kh = db.KHACHHANGs.SingleOrDefault(n => n.TenDN == tendn && n.Matkhau == matkhau);
                    if(kh != null)
                    {
                        Session["Taikhoan"] = kh;
                        Session["MaKH"] = kh.MaKH.ToString();
                        Session["TenDN"] = kh.TenDN.ToString();
                        return RedirectToAction("Index", "TrangChu");
                    }
                    else
                    {
                        ViewBag.Thongbao = "Tên đăng nhập hoăc mật khẩu không đúng";
                    }
            }
            return View();
        }
        public ActionResult Dangxuat()
        {
            Session.Clear();
            Session.RemoveAll();
            return RedirectToAction("Index","TrangChu");
        }
    }
}

WebApplication11/Controllers/TrangChuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication11.Models;

using PagedList;
using PagedList.Mvc;
namespace WebApplication11.Controllers
{
    public class TrangChuController : Controller
    {
        // GET: TrangChu
        public ActionResult Index(int ? page)
        {
            int pageSize = 6;
            int pageNumber = (page ?? 1);

            var Dochoimoi = Laydochoimoi(12);
            return View(Dochoimoi.ToPagedList(pageNumber, pageSize));
        }
        QLBANDOCHOIEntities1 data = new QLBANDOCHOIEntities1();
        private List<DOCHOI> Laydochoimoi(int count)
        {
            return data.DOCHOIs.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        
        public ActionResult Chude()
        {
            var chude = from s in data.CHUDEs select s;
            return View(chude);
        }
        public ActionResult Thuonghieu()
        {
            var th = from q in data.THUONGHIEUx select q;
            return View(th);
        }

        public ActionResult SPTheochude(int id)
        {
            var dochoi = from s in data.DOCHOIs where s.MaCD == id select s;
            return View(dochoi);
        }
        public ActionResult SPTheothuonghieu(int id)
        {
            var dochoi = from s in data.DOCHOIs where s.MaTH == id select s;
            return View(dochoi);
        }
        public ActionResult Laytenchude(int id)
        {
            var chude = from s in data.CHUDEs where s.MaCD == id select s;
            return View(chude);
        }

       

        public ActionResult Laytenthuonghieu(int id)
        {
            var th = from q in data.THUONGHIEUx where q.MaTH == id select q;
            return View(th);
        }

        public ActionResult Details(int id)
        {
            var dochoi = from s in data.DOCHOIs where s.MaDC == id select s;
            return View(dochoi.Single());
        }

        public ActionResult Lienhe()
        {
            return View();
        }

    }
}

WebApplication11/Views/TrangChu/Chude.cshtml
@model IEnumerable<WebApplication11.Models.CHUDE>
@foreach (var item in Model)
{
    <a href="@Url.Action("SPTheochude", "TrangChu", new { id =item.MaCD})" class="list-group-item">
        @item.Tenchude
    </a>
}

WebApplication11/Views/TrangChu/Index.cshtml
@using WebApplication11.Models;
@using PagedList.Mvc;
@model PagedList.PagedList<DOCHOI>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="col-lg-9">

    <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1" class=""></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2" class=""></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img class="d-block img-fluid" src="~/Data/images/anh1.png" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="~/Data/images/anh2.png" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="~/Data/images/anh3.png" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="row">
        @foreach (var dochoi in Model)
            {
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="img-thumbnail">
                    <a href="@Url.Action("Details", "TrangChu", new { id = dochoi.MaDC })">                       
                        <img alt="@dochoi.TenDC" src="@dochoi.Hinhminhhoa" width="250" height="300"/>
                    </a>
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @dochoi.TenDC
                        </h4>
                        <p></p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">★ ★ ★ ★ ☆</small>
                    </div>
                </div>
            </div>
        }
    </div> 
    <!-- /.row -->
    @*Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/@Model.PageCount;*@

    <div class="MenuTrang">
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
    </div>
    <style>
        .MenuTrang li {
            display: inline;
        }
    </style>
</div>

WebApplication11/Views/TrangChu/Laytenchude.cshtml
@model IEnumerable<WebApplication11.Models.CHUDE>
@foreach (var item in Model)
{
    <a id ="item.MaCD">
        @item.Tenchude
    </a>
}

WebApplication11/Views/TrangChu/Laytenthuonghieu.cshtml
@model IEnumerable < WebApplication11.Models.THUONGHIEU>
@foreach (var item in Model)
{
    <a id="item.MaTH">
        @item.Tenthuonghieu
    </a>
}

WebApplication11/Views/TrangChu/Lienhe.cshtml
@{
    ViewBag.Title = "Lienhe";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/ContentMap/style.css" rel="stylesheet" />
<link href="~/Content/ContentMap/font-awesome.css" rel="stylesheet" />
<script src="~/Scripts/jquery.min.js"></script>
<script src="~/Scripts/main.js"></script>
<script src="~/Scripts/bootstrap-3.1.1.min.js"></script>
<script src="~/Scripts/simpleCart.min.js"></script>
<div class="col-lg-9">
    <div class="header" style="color:white;text-align:center;font-size:28px;padding-top:10px">
        Mail Us
    </div>
    <div class="content">
                    <div class="map-w3">
                        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1959.4519135842756!2d106.71890076875027!3d10.818671546432196!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3175289c82518457%3A0x4b7f5ccf7143b946!2zTmjDoCBuZ2jhu4kgLSBLaMOhY2ggc-G6oW4gQ8O0bmcgxJBvw6BuIFRoYW5oIMSQYQ!5e0!3m2!1svi!2s!4v1523936360854" allowfullscreen></iframe>
                    </div>
                    <div class="mail-bottom">
                        <h4>Liên hệ với chúng tôi</h4>
                        <form action="#" method="post">
                            <input style="background:white" type="text" value="Tên" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Name';}" required="">
                            <input style="background:white" type="email" value="Email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Email';}" required="">
                            <input style="background:white" type="text" value="Điện thoại" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Telephone';}" required="">
                            <textarea style="background:white" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Message...';}" required="">Nội dung...</textarea>
                            <input type="submit" value="Submit">
                            <input type="reset" value="Clear">
                        </form>
                    </div>
        </div>
        <!--contact-->
    </div>

WebApplication11/Views/TrangChu/SPTheochude.cshtml
@{
    ViewBag.Title = "SPTheochude";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="col-lg-9">

    <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1" class=""></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2" class=""></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img class="d-block img-fluid" src="~/Data/images/anh1.png" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="~/Data/images/anh2.png" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="~/Data/images/anh3.png" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="header" style="color:white;text-align:center;font-size:28px;padding-top:5px">
        @Html.Action("Laytenchude", "TrangChu")
    </div>

    <div class="row" style="padding-top:10px;padding-left:25px">    
        @foreach (var dochoi in Model)
            {
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="img-thumbnail">
                    <a href="@Url.Action("Details", "TrangChu", new { id = dochoi.MaDC })">
                        ;
                        <img alt="@dochoi.TenDC" src="@dochoi.Hinhminhhoa" width="200" height="250"/>
                    </a>
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @dochoi.TenDC
                        </h4>
                        <p></p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">★ ★ ★ ★ ☆</small>
                    </div>
                </div>
            </div>
        }
    </div>
    <!-- /.row -->
    <script src="~/ScriptsAdmin/bootstrap.min.js"></script>
    <script src="~/ScriptsAdmin/custom.js"></script>

</div>

WebApplication11/Views/TrangChu/SPTheothuonghieu.cshtml
@{
    ViewBag.Title = "SPTheothuonghieu";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<div class="col-lg-9">

    <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1" class=""></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2" class=""></li>
        </ol>
        <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
                <img class="d-block img-fluid" src="~/Data/images/anh1.png" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="~/Data/images/anh2.png" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block img-fluid" src="~/Data/images/anh3.png" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

    <div class="header" style="color:white;text-align:center;font-size:28px;padding-top:5px">
        @Html.Action("Laytenthuonghieu", "TrangChu")
    </div>

    <div class="row" style="padding-top:10px;padding-left:25px">
        @foreach (var dochoi in Model)
            {
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="img-thumbnail">
                    <a href="@Url.Action("Details", "TrangChu", new { id = dochoi.MaDC })">
                        ;
                        <img alt="@dochoi.TenDC" src="@dochoi.Hinhminhhoa" width="200" height="250" />
                    </a>
                    <div>
                        <br />
                        <h4 style="text-align:center">
                            @dochoi.TenDC
                        </h4>
                        <p></p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">★ ★ ★ ★ ☆</small>
                    </div>
                </div>
            </div>
        }
    </div>
    <!-- /.row -->
    <script src="~/ScriptsAdmin/bootstrap.min.js"></script>
    <script src="~/ScriptsAdmin/custom.js"></script>
</div>

WebApplication11/Views/TrangChu/Thuonghieu.cshtml
@model IEnumerable < WebApplication11.Models.THUONGHIEU>

@foreach (var item in Model)
{
    <a href="@Url.Action("SPTheothuonghieu", "TrangChu", new { id =item.MaTH})" class="list-group-item">
        @item.Tenthuonghieu
    </a>

}

WebApplication11/Views/TrangChu/View.cshtml
<div class="col-lg-9">
    <div class="left_content">
        <div class="span1_of_1">
            <!-- start product_slider -->
            <div class="product-view">
                <div class="product-essential">
                    <div class="product-img-box">
                        <div class="more-views">
                            <div class="more-views-container">
                                <ul>
                                    <li>
                                        <a class="cs-fancybox-thumbs" data-fancybox-group="thumb" href="" title="" alt="">
                                            <img src="" src_main="" title="" alt="" />
                                        </a>
                                    </li>
                                    <li>
                                        <a class="cs-fancybox-thumbs" data-fancybox-group="thumb" href="" title="" alt="">
                                            <img src="" src_main="" title="" alt="" />
                                        </a>
                                    </li>
                                    <li>
                                        <a class="cs-fancybox-thumbs" data-fancybox-group="thumb" href="" title="" alt="">
                                            <img src="" src_main="" title="" alt="" />
                                        </a>
                                    </li>
                                    <li>
                                        <a class="cs-fancybox-thumbs" data-fancybox-group="thumb" href="" title="" alt="">
                                            <img src="" src_main="" title="" alt="" />
                                        </a>
                                    </li>
                                    <li>
                                        <a class="cs-fancybox-thumbs" data-fancybox-group="thumb" href="" title="" alt="">
                                            <img src="" src_main="" title="" alt="" />
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="product-image">
                            <a class="cs-fancybox-thumbs cloud-zoom" rel="adjustX:30,adjustY:0,position:'right',tint:'#202020',tintOpacity:0.5,smoothMove:2,showTitle:true,titleOpacity:0.5" data-fancybox-group="thumb" href="~/images/imagesDetail/0001-2.jpg" title="Women Shorts" alt="Women Shorts">
                                <img src="~/images/imagesDetail/0001-2.jpg" alt="Women Shorts" title="Women Shorts" />
                            </a>
                        </div>
                        <script type="text/javascript">
						var prodGallery = jQblvg.parseJSON('{"prod_1":{"main":{"orig":"~/images/imagesDetail/0001-2.jpg","main":"~/images/imagesDetail/large/0001-2.jpg","thumb":"~/images/imagesDetail/small/0001-2.jpg","label":""},"gallery":{"item_0":{"orig":"~/images/imagesDetail/0001-2.jpg","main":"~/images/imagesDetail/large/0001-2.jpg","thumb":"~/images/imagesDetail/small/0001-2.jpg","label":""},"item_1":{"orig":"~/images/imagesDetail/0001-1.jpg","main":"~/images/imagesDetail/large/0001-1.jpg","thumb":"~/images/imagesDetail/small/0001-1.jpg","label":""},"item_2":{"orig":"~/images/imagesDetail/0001-5.jpg","main":"~/images/imagesDetail/large/0001-5.jpg","thumb":"~/images/imagesDetail/small/0001-5.jpg","label":""},"item_3":{"orig":"~/images/imagesDetail/0001-3.jpg","main":"~/images/imagesDetail/large/0001-3.jpg","thumb":"~/images/imagesDetail/small/0001-3.jpg","label":""},"item_4":{"orig":"~/images/imagesDetail/0001-4.jpg","main":"~/images/imagesDetail/large/0001-4.jpg","thumb":"~/images/imagesDetail/small/0001-4.jpg","label":""}},"type":"simple","video":false}}'),
						    gallery_elmnt = jQblvg('.product-img-box'),
						    galleryObj = new Object(),
						    gallery_conf = new Object();
						    gallery_conf.moreviewitem = '<a class="cs-fancybox-thumbs" data-fancybox-group="thumb"  href=""  title="" alt=""><img src="" src_main="" title="" alt="" /></a>';
						    gallery_conf.animspeed = 200;
						jQblvg(document).ready(function() {
						    galleryObj[1] = new prodViewGalleryForm(prodGallery, 'prod_1', gallery_elmnt, gallery_conf, '.product-image', '.more-views', 'http:');
						        jQblvg('.product-image .cs-fancybox-thumbs').absoluteClick();
						    jQblvg('.cs-fancybox-thumbs').fancybox({ prevEffect : 'none',
						                             nextEffect : 'none',
						                             closeBtn : true,
						                             arrows : true,
						                             nextClick : true,
						                             helpers: {
						                               thumbs : {
						                                   position: 'bottom'
						                               }
						                             }
						                             });
						    jQblvg('#wrap').css('z-index', '100');
						            jQblvg('.more-views-container').elScroll({type: 'vertical', elqty: 4, btn_pos: 'border', scroll_speed: 400 });

						});

						function initGallery(a,b,element) {
						    galleryObj[a] = new prodViewGalleryForm(prods, b, gallery_elmnt, gallery_conf, '.product-image', '.more-views', '');
						};
                        </script>
                    </div>
                </div>
            </div>
            <!-- end product_slider -->
        </div>
        <!-- start span1_of_1 -->
        <div class="span1_of_1_des">
            <div class="desc1">
                <h3>@Model.TenDC</h3>
                <h5>Rs. 499 <span>@Model.Dongia</span>  <a href="#">click for offer</a></h5>
                <div class="available">
                    <div class="btn_form">
                        <form>
                            <input type="submit" value="buy now" title="" />
                        </form>
                    </div>
                    <span><a href="@Url.Action("Dangnhap","Nguoidung")">login to save in wishlist </a></span>
                    <p>It is a long established fact that a reader will be distracted by the readable contentContrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from of a page when looking at its layout.</p>
                </div>
                <div class="share-desc">
                    <div class="share">
                        <h4>Share Product :</h4>
                        <ul class="share_nav">
                            <li><a href="#"><img src="~/images/imagesDetail/facebook.png" title="facebook"></a></li>
                            <li><a href="#"><img src="~/images/imagesDetail/twitter.png" title="Twiiter"></a></li>
                            <li><a href="#"><img src="~/images/imagesDetail/rss.png" title="Rss"></a></li>
                            <li><a href="#"><img src="~/images/imagesDetail/gpluse.png" title="Google+"></a></li>
                        </ul>
                    </div>
                    <div class="clear"></div>
                </div>
            </div>
        </div>
        <div class="clear"></div>
        <!-- start left content_bottom -->
        <div class="left_content_btm">
            <p class="para">@Model.Mota</p>
            <!-- start tabs -->
            <section class="tabs">
                <input id="tab-1" type="radio" name="radio-set" class="tab-selector-1" checked="checked">
                <label for="tab-1" class="tab-label-1">overview</label>

                <input id="tab-2" type="radio" name="radio-set" class="tab-selector-2">
                <label for="tab-2" class="tab-label-2">consumer</label>

                <input id="tab-3" type="radio" name="radio-set" class="tab-selector-3">
                <label for="tab-3" class="tab-label-3">semiconductor</label>

                <div class="clear-shadow"></div>

                <div class="content">
                    <div class="content-1">
                        <p class="para top"><span>@Model.TenDC</span> @Model.Mota</p>
                        <ul>
                            <li>Research</li>
                            <li>Design and Development</li>
                            <li>Porting and Optimization</li>
                            <li>System integration</li>
                            <li>Verification, Validation and Testing</li>
                            <li>Maintenance and Support</li>
                        </ul>
                        <div class="clear"></div>
                    </div>
                    <div class="content-2">
                        <p class="para"><span>WELCOME </span> Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections </p>
                        <ul class="qua_nav">
                            <li>Multimedia Systems</li>
                            <li>Digital media adapters</li>
                            <li>Set top boxes for HDTV and IPTV Player applications on various Operating Systems and Hardware Platforms</li>
                        </ul>
                    </div>
                    <div class="content-3">
                        <p class="para top"><span>LOREM IPSUM</span> There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined </p>
                        <ul>
                            <li>Research</li>
                            <li>Design and Development</li>
                            <li>Porting and Optimization</li>
                            <li>System integration</li>
                            <li>Verification, Validation and Testing</li>
                            <li>Maintenance and Support</li>
                        </ul>
                        <div class="clear"></div>
                    </div>
                </div>
            </section>
            <!-- end tabs -->
        </div>
        <!-- end left content_bottom -->
    </div>
    <link href="~/Content/ContentDetails/style.css" rel="stylesheet" />
    <script src="~/Scripts/ScriptsDetails/jquery.min.js"></script>
    <link href="~/Content/ContentDetails/productviewgallery.css" rel="stylesheet" />
    <script src="~/Scripts/ScriptsDetails/cloud-zoom.1.0.3.min.js"></script>
    <script src="~/Scripts/ScriptsDetails/productviewgallery.js"></script>
    <script src="~/Scripts/ScriptsDetails/easing.js"></script>

</div>